[workspace]
authors = ["Markus Groissböck <markus.groissboeck@gmx.at>"]
channels = ["conda-forge"]
name = "PyPSA-X"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pypsa = ">=1.0.7,<2"
tsam = ">=3.1.0,<4"
grpcio = "1.73.1.*"
openpyxl = ">=3.1.5,<4"
