[workspace]
authors = ["Markus Groissböck <markus.groissboeck@gmx.at>"]
channels = ["conda-forge"]
name = "PyPSA-X"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pypsa = ">=1.2.4,<2"
tsam = ">=4.0.0,<5"
atlite = ">=0.6.1,<0.7"
xlrd = ">=2.0.2,<3"
openpyxl = ">=3.1.5,<4"
python = "==3.12.13"
cdsapi = ">=0.7.7,<0.8"
salib = ">=1.5.2,<2"
google-cloud-storage = ">=3.12.0,<4"
requests = ">=2.34.2,<3"
linopy = ">=0.9.0,<0.10"
pre_commit = ">=4.6.0,<5"
python-calamine = ">=0.6.1,<0.7"
pandas = "==2.3.3"
highspy = "==1.15.1"
numba = ">=0.66.0,<0.67"

[pypi-dependencies]
pypsa = { version = "*", extras = ["excel"] }
pandapower = ">=3.1.2, <4"
pandapipes = ">=0.12.0, <0.13"
numpy-financial = ">=1.0.0, <2"
pypower = ">=5.1.21, <6"
highspy = "*"
